//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidHeight.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidHeight.Resources.rsControl", typeof(rsControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string cmbActions {
            get {
                return ResourceManager.GetString("cmbActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes.
        /// </summary>
        internal static string cmbCauses {
            get {
                return ResourceManager.GetString("cmbCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string cmbShift {
            get {
                return ResourceManager.GetString("cmbShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Model.
        /// </summary>
        internal static string cmbSubModel {
            get {
                return ResourceManager.GetString("cmbSubModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacroScope.
        /// </summary>
        internal static string rdbMacroScope {
            get {
                return ResourceManager.GetString("rdbMacroScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        internal static string rdbPrime {
            get {
                return ResourceManager.GetString("rdbPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Confirm.
        /// </summary>
        internal static string rdbReConfirm {
            get {
                return ResourceManager.GetString("rdbReConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Height.
        /// </summary>
        internal static string rdbSH {
            get {
                return ResourceManager.GetString("rdbSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand Off.
        /// </summary>
        internal static string rdbSO {
            get {
                return ResourceManager.GetString("rdbSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHX.
        /// </summary>
        internal static string rdbVHX {
            get {
                return ResourceManager.GetString("rdbVHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder Height.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand Off.
        /// </summary>
        internal static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cavity.
        /// </summary>
        internal static string txtCav {
            get {
                return ResourceManager.GetString("txtCav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Limit.
        /// </summary>
        internal static string txtCenterLimit {
            get {
                return ResourceManager.GetString("txtCenterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPK Lower.
        /// </summary>
        internal static string txtCPKLower {
            get {
                return ResourceManager.GetString("txtCPKLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPK Upper.
        /// </summary>
        internal static string txtCPKUpper {
            get {
                return ResourceManager.GetString("txtCPKUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Trickness.
        /// </summary>
        internal static string txtDie {
            get {
                return ResourceManager.GetString("txtDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string txtEN {
            get {
                return ResourceManager.GetString("txtEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string txtHeight {
            get {
                return ResourceManager.GetString("txtHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName.
        /// </summary>
        internal static string txtHostName {
            get {
                return ResourceManager.GetString("txtHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string txtInput {
            get {
                return ResourceManager.GetString("txtInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string txtLine {
            get {
                return ResourceManager.GetString("txtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        internal static string txtLotNo {
            get {
                return ResourceManager.GetString("txtLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit.
        /// </summary>
        internal static string txtLower {
            get {
                return ResourceManager.GetString("txtLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string txtMeasurement {
            get {
                return ResourceManager.GetString("txtMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string txtModel {
            get {
                return ResourceManager.GetString("txtModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad.
        /// </summary>
        internal static string txtPad {
            get {
                return ResourceManager.GetString("txtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad/Column.
        /// </summary>
        internal static string txtPadPerCol {
            get {
                return ResourceManager.GetString("txtPadPerCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string txtQty {
            get {
                return ResourceManager.GetString("txtQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string txtRemark {
            get {
                return ResourceManager.GetString("txtRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string txtRow {
            get {
                return ResourceManager.GetString("txtRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Upper.
        /// </summary>
        internal static string txtSDUpper {
            get {
                return ResourceManager.GetString("txtSDUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string txtSeq {
            get {
                return ResourceManager.GetString("txtSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNo.
        /// </summary>
        internal static string txtSerialNo {
            get {
                return ResourceManager.GetString("txtSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stencil.
        /// </summary>
        internal static string txtStencil {
            get {
                return ResourceManager.GetString("txtStencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PCCA.
        /// </summary>
        internal static string txtTotalPCCA {
            get {
                return ResourceManager.GetString("txtTotalPCCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper  Limit.
        /// </summary>
        internal static string txtUpper {
            get {
                return ResourceManager.GetString("txtUpper", resourceCulture);
            }
        }
    }
}
